### PR TITLE
WORKING

### PR DESCRIPTION
**Pull request by abuchohan**

### CODE REVIEW

**Comment by liamhenshall** [comment]
Top 5 museum attractions

Museums

The Whitworth gallery

With around 55,000 unique pieces of art, the Whitworth is the perfect day out for anyone with an eye for beauty. They’re currently displaying an Andy Warhol exhibition displaying his most prevalent work.



Museum of science and industry

Manchester has had a crucial role in the development of industry and it home to the first computer! Here you will see trains, aeroplanes and more! Originally the Liverpool Road Station you will feel industry in its atmosphere .



National Football museum

Home to two of the biggest teams in the world, Manchester is arguably the home of football and there’s nowhere better for a footy fanatic to visit than here. With beautiful architecture the building stands tall containing compelling and intriguing facts you probably didn’t know



Manchester museum

Being the largest university museum this place has more than enough to provoke thought, discover our eco-system and even touch the moon! There’s 4.5 million things to learn about so you it’s the perfect day out for lovers of natural history and science.



Manchester Art Gallery

This stunning building is home to many paintings, sketches and sculptures. Open 7 days a week and free to enter with beauty hidden around every corner there’s always something to catch your eye!



________________________________

**Comment by liamhenshall** [comment]
don't get caught up in all of the excitement of university and forget the education part, if you want to make it to 2nd year make sure you put some time aside to revise! Of course it's not the most interesting part of uni but it's definitely essential!


________________________________

**Comment by abuchohan** [comment]
<div class="content-box middle">
        <hr>
         <div class="icons">
        <a href="health.php" title="#" class="healthicon"><p>Health</p></a>
        <a href="food.php" title="#" class="foodicon"><p>Food</p></a>
        <a href="social.php" title="#" class="sportsicon"><p>Sports</p></a>
            </div>
              </div>



________________________________

**Comment by abuchohan** [comment]
@import url('reset.css');
/*----------------------------Layout---------------------------------*/
html {
    font-family: 'Varela Round', sans-serif;
    -webkit-text-size-adjust: 100%;
    -ms-text-size-adjust:     100%;
    background: #f4f4f4;
}
body {
    box-sizing: border-box;
    margin: 0;
    padding: 0;
    color: black;
    line-height: 1.5;
    font-size: 100%;
}
h1,h2,h3,h4,p {
    margin: 0;
    padding: 0;
    font-size: 1.1rem;
    font-weight: normal;
}
img {
    max-width: 100%; height: auto;
}
a {
    text-decoration: none; color: deepskyblue;
}


.page-content {/*padding: 0 25px;*/ max-width: 1111px; margin: 0 auto;}
.page-content p {padding-bottom: 15px;}
.page-content a:hover {color: #004a97;}
.header h1 {
    font-size: 3.9rem;
    padding: 100px 30px;
    text-align: center;
    color: aliceblue;
    background-attachment: fixed;
    background-repeat: no-repeat;
    background-size: cover;
    background-position: center;
}
.header.food h1{
    background-image: url("images/food.jpg");
}
.header.finance h1 {
    background-image: url("images/money.jpg");
}
.header.nclubs h1 {
    background-image: url("images/money.jpg");
}
.header.hallshouses h1 {
    background-image: url("images/money.jpg");
}
.header.health h1 {
    background-image: url("images/money.jpg");
}
.header.creators h1 {
    background-image: url("images/money.jpg");
}
.header.transport h1 {
    background-image: url("images/test2.jpg");
}

.page-content h2 {
    font-size: 1.6rem;
    font-weight: bold;
    color:#004a97;
    padding-bottom: 15px;
    padding-top: 15px;
    text-align:center;
}
.page-content h3 {
    font-weight: bold;
}
.page-content ul li{list-style: none;}

.main-content {
    background: -moz-linear-gradient(top,  rgba(125,185,232,0.31) 1%, rgba(125,185,232,0.39) 12%, rgba(52,146,207,0.94) 92%, rgba(52,146,207,1) 100%);
background: -webkit-linear-gradient(top,  rgba(125,185,232,0.31) 1%,rgba(125,185,232,0.39) 12%,rgba(52,146,207,0.94) 92%,rgba(52,146,207,1) 100%);
background: linear-gradient(to bottom,  rgba(125,185,232,0.31) 1%,rgba(125,185,232,0.39) 12%,rgba(52,146,207,0.94) 92%,rgba(52,146,207,1) 100%);
filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#4f7db9e8', endColorstr='#3492cf',GradientType=0 );
}

/*.page-content {background: #f9f9f9;}*/
/*.page-article{padding-top: 50px;}*/

.page-footer {background-color:#333333;color: aliceblue;padding: 20px;}
.page-footer a:hover{ color: aliceblue; }


.page-footer {
    background-color:#333333;
    color: aliceblue;
    padding: 10px 0px 10px 0px;
    display: inline-flex;
    width: 100%;
    text-align: center;
}

.pre-footer a{
    padding: 15px;
    background:#878787;
    color: aliceblue;
    text-align: center;
    display: block;
}

.pre-footer a:hover{
    background: #004a97;
}

.author {
    font-size: 10px;
}

.heroimage img {

border: solid red 1px;
}
/*--------------Accessibility-------------------------------*/

.skiplinks {display: none;}
.screen-reader-text {
    clip: rect(1px, 1px, 1px, 1px);
    position: absolute !important;
    height: 1px;
    width: 1px;
    overflow: hidden;
}

.screen-reader-text:hover,
.screen-reader-text:active,
.screen-reader-text:focus {
    background-color: #f1f1f1;
    border-radius: 3px;
    box-shadow: 0 0 2px 2px rgba(0, 0, 0, 0.6);
    clip: auto !important;
    color: #21759b;
    display: block;
    font-size: 14px;
    font-weight: bold;
    height: auto;
    left: 5px;
    line-height: normal;
    padding: 15px 23px 14px;
    text-decoration: none;
    top: 5px;
    width: auto;
    z-index: 100000;

}

/*------ Navigation ------*/
.menu-link { display: none;}
.menu {
    background-color: #004a97;

}
.menu ul {
  padding: 0px;
  margin: 0px;
  list-style: none;
  position: relative;
}

.menu > ul {
text-align: center;

}
.sub-menu {
    text-align: left;


}
.menu ul li {
    padding: 0px;
}
.menu > ul > li {
    display: inline-block;
}
.menu ul li a {
    display: block;
    text-decoration: none;
    color: #fff;
}
.menu ul li > a {
    padding: 20px;
}

.skiplinks {display: none;}
.menu ul li > a:hover {
    background-color: #47a6cc;
}

.menu ul ul {
  display: none;
  position: absolute;
  top:100%;
  min-width: 160px;
}

.menu ul li:hover > ul { display: block; }
.menu ul ul > li { position: relative; }
.menu ul ul > li a { padding: 20px; height: auto; background-color: #3492cf;}
.menu ul ul > li a:hover { background-color: #47a6cc; color: #fff; }
.menu ul ul ul { position: absolute; left: 100%; top:0; }


/*-----------media------------------*/

@media screen and (max-width: 1150px) {
    .menu ul li a  {
        padding: 20px 10px;
    }
}

@media screen and (max-width: 881px) {
    .menu ul li a  {
        padding: 20px 10px;
    }
}

@media screen and (max-width: 792px) {
    .menu ul li a  {
        padding: 20px 8px;
    }
}

@media all and (max-width: 768px) {
  a.menu-link { display: block;
      color: #fff;
      background-color: #777777;
      text-decoration: none;
      padding: 20px;
      text-align: center;
    }
    .sub-menu {
    text-align: left;
    padding: 8px 0;
    background-color: #f4f4f4;
    border: 1px solid #fff;

}

    .menu ul {text-align: left;}
  .menu { clear: both; min-width: inherit; float: none;}
  .menu, .menu > ul ul { overflow: hidden; max-height: 0; background-color: #004a97; }
  .menu > li > ul.sub-menu { padding: 0px; border: none; }
  .menu.active, .menu > ul ul.active { max-height: 100%; }
  .menu ul { display: inline; }
  .menu > ul { border-top: 1px solid #808080; }
  .menu li, .menu > ul > li { display: block; }
  .menu li a { color: #000; display: block; padding: 0.8em;   border-bottom: .1px solid #fff; position: relative; }
  .menu li.has-sub-menu > a:after {
    content: "+";
    position: absolute;
    top: 0;
    right: 0;
    display: block;
    font-size: 1.5em;
    padding: 0.6em 0.5em;
  }
  .menu li.has-sub-menu > a.active:after {
    content: "-";
  }
  .menu ul ul > li a { background-color: grey ; padding: 19px 18px 19px 50px; }
  .menu ul ul, .menu ul ul ul { display: inherit; position: relative; left: auto; top:auto; border:none; }
}
/*----------------------------------------Content-BOx----------------------------------------------*/

.content-box{
    background: #f9f9f9;
    padding: 20px 20px;
}
.content-box.first{
    padding: 20px 0px;
}
.content-box.first .page-article1{
    padding: 0 20px;
}


@media screen and (min-width:1111px) {
    .content-box{
        border-radius: 16px;
    }
   .content-box.middle{
    margin-top: 30px;
    margin-bottom: 30px;
}
    .content-box.first {
        background: none;
        color: black;
        padding-top: 30px;

    }
    .content-box.first ol{
        color: white;
    }
    .content-box.first a{
        color: #004a97;
    }
    .content-box.first a:hover{
        color: white;
    }
    .content-box.first .image {
        border: 15px solid white;
    border-radius: 500px;
    background: white;
    }
    .content-box.first .page-article1 {
        margin-right: 80px;
    }
    .content-box.first .page-article1.box{
        background: #f9f9f9;
        margin: 0;
        padding: 0 20px 0 20px;
    }
}
.content-box.first a{
    text-decoration:underline;
}

/*-------------------------------Flexbox-----------------------------------*/
.thirds div {
    width: 100%;
    display: inline-flex;
    padding: 15px;
height: 200px;
flex-wrap: no-wrap;
}

@media screen and (min-width: 769px) {
.thirds div {
        max-width: 30%;
        float: left;
    border: solid;
    }
    .header h1 {
        font-size: 5rem;
/*        padding-top: px;*/
    padding-bottom: 150px;
    }
    .main-content  {
       display: flex;
       flex-wrap: wrap;
    }
    .page-article {
        display: flex;
        flex-wrap: wrap;
        flex-direction: row;
        justify-content: space-between;
    }

    .page-article1 {
        flex: 1;
        min-width: 330px;
        max-width: 500px;
        padding-right:20px;

    }
    .page-article1.box{
        background: #f9f9f9;
        border-radius: 16px;
    }
    .page-article1-text{
        padding-top: 20px;
    }
    .image {
        flex: 1;
        max-width: 300px;
        max-height: 300px;
        background: ;
    }
    .content-box.first .image{
    margin: 50px 40px;
    }
    .content-box.middle .image{
        padding-top: 90px;
        margin-right: 50px;
    }
    .content-box.last .image{
      margin-right: 50px;
    }
    .content-box.first .page-article1 {
        padding-top: 35px;
    }
}

/*-----------------------------------THE HORIZONTAL LINE----------------------------------*/
@media screen and (max-width:1111px){
     hr{
        margin: 20px 50px;

    }
}
@media screen and (min-width:1111px){
    hr{
        margin: 0 600px;
    }
}
/*-----------------------------------IMAGE SIZING---------------------------------------------*/
@media screen and (min-width:943px){
    .content-box.first .image{
    margin-left: 100px;
    }
    .content-box.middle .image{
        margin-right: 100px;
    }
    .content-box.last .image{
      margin-right: 100px;
    }
}

@media screen and (max-width:1039px){
    .image{
        margin: 0 auto;
    }
}
.page-article1 ol {
        text-align: center;
        list-style-position: inside;
        padding: 0;
    }
/*RIGHT HAND FLOATING IMAGES CODE*/
@media screen and (max-width:769px){
    .image {
    max-width: 300px;
        }

}
.content-box.middle .image {
    order: 2;
}
.content-box.last .image {
    order: 2;
}

/*-------------------------------Content MARGIN ADAPTER---------------------------------*/

@media screen and (min-width:1111px){
    .page-content{margin-top: 10px;margin-bottom: 10px;}
}
@media screen and (min-width:1300px){
    .page-content{margin-top: 60px;margin-bottom: 60px;}
}
/*-----------------------ICONS NORMAL-----------------------*/



.icons {
    display: flex;
    flex-wrap: wrap;
    list-style: none;
    justify-content: space-around;
    padding-top: 30px;

}


/* Icon hover over   */
.universityicon {
    background: transparent url("icons/university.png") center top no-repeat;
    width: 128px;
    height: auto;
}
.financeicon {
    background: transparent url("icons/finance.png") center top no-repeat;
    width: 128px;
    height: auto;
}
.societiesicon {
    background: transparent url("icons/societies.png") center top no-repeat;
    width: 128px;
    height: auto;
}
.appsicon {
    background: transparent url("icons/app.png") center top no-repeat;
    width: 128px;
    height: auto;
}
/*------------------IVOS DESPRET CHANGE 7:55am----------------*/
.foodicon {
    background: transparent url("icons/food.png") center top no-repeat;
    width: 128px;
    height: auto;
}
.clubsicon {
    background: transparent url("icons/nightclubs.png") center top no-repeat;
    width: 128px;
    height: auto;
}
.museumsicon {
    background: transparent url("icons/museum.png") center top no-repeat;
    width: 128px;
    height: auto;
}
.coursesicon {
    background: transparent url("icons/courses.png") center top no-repeat;
    width: 128px;
    height: auto;
}
.socialicon {
    background: transparent url("icons/social.png") center top no-repeat;
    width: 128px;
    height: auto;
}
.entertainmenticon {
    background: transparent url("icons/entertainment.png") center top no-repeat;
    width: 128px;
    height: auto;
}
.sportsicon {
    background: transparent url("icons/sports.png") center top no-repeat;
    width: 128px;
    height: auto;
}
.healthicon {
    background: transparent url("icons/health.png") center top no-repeat;
    width: 128px;
    height: auto;
}

.icons p {
    color: black;
    font-weight: bold;
text-align: center;
    margin-top: 140px
}

.icons p:hover {
  color: black;
}

/*  icon hover over state */
.universityicon:hover {
 background-image: url(icons/universityblue.png);
}
.financeicon:hover {
 background-image: url(icons/financeblue.png);
}
.societiesicon:hover {
 background-image: url(icons/societiesblue.png);
}
.appsicon:hover {
 background-image: url(icons/appblue.png);
}

.foodicon:hover {
 background-image: url(icons/foodblue.png);
}
.clubsicon:hover {
 background-image: url(icons/nightclubsblue.png);
}
.museumsicon:hover {
 background-image: url(icons/museumblue.png);
}
.coursesicon:hover {
 background-image: url(icons/coursesblue.png);
}
.socialicon:hover {
 background-image: url(icons/socialblue.png);
}
.entertainmenticon:hover {
 background-image: url(icons/entertainmentblue.png);
}
.sportsicon:hover {
 background-image: url(icons/sportsblue.png);
}
.healthicon:hover {
 background-image: url(icons/healthblue.png);
}

/*-------------------------------ICONS MOBILE-----------------------------*/
@media screen and (max-width:760px){
    .icons {
        background: ;
        display: flex;
    flex-wrap: wrap;
    list-style: none;
    padding-bottom: 20px;
   justify-content: space-around;
    }
    .icons li{
        padding: 10px;
        flex: 1;
        max-height: 120px;
        max-width: 120px;
        min-width: 80px;
    }
}

/*-------------------------PAGE CONTENT CARDS------------------------------------*/

.page-content-cards {
  max-width: 1111px;
  display: flex;
  flex-wrap: wrap;
  margin:0 auto;
   /* padding-top: 70px;
  padding-bottom: 70px;*/
}
.page-article2 {
  min-width: 100%;
  display: flex;
  flex-direction: column;
}

.small-image {
  align-self: center;
  width: 100%;
  height: auto;
}

@media screen and (min-width: 600px) {
  .page-article2 {
    width: 48%;
/* margin: 0 auto 2%;*/
    min-width: 0;
  }
    .page-content-cards{
        justify-content: space-between;
    }
}
.page-article2 h2{
    padding-top: 20px;
}


/*-----------------------------------------------------
                ABOUT US PAGE
--------------------------------------------------------*/



.members {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-around;
    text-align: center;
    padding-top: 70px;
    padding-bottom: 97px;
}
.member-img{
    border: 15px solid white;
    border-radius: 500px;
    background: white;
    max-height: 240px;
    max-width: 240px;
}
.member-text{
    max-width: 240px;
    text-align: center;
    margin: 0 auto;
}
.member p{
    color: aliceblue;
}
.member h3 {
    color: #696969;
}
.member{
    padding: 10px;
}
.member h2{
    color: aliceblue;
}




________________________________

**Comment by liamhenshall** [comment]
.sub-heading {
font-size: 1.3rem;
    font-weight: bold;
    color:white;
    padding-bottom: 5px;
    padding-top: ;
    text-align:
}
.main-heading {
font-size: 2.4rem;
    font-weight: bold;
    color:white;
    padding-bottom: ;
    padding-top: 100px;
    text-align:
}
.home-slideshow {
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
}
.home-background {
background-image: url(images/boller-surprise.jpg);
background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
height: px;
text-align: center;
color: white
}
.home-icon {
max-width: 50%;
margin: auto;
display: block;
border-radius: 10px;
padding: 5px;
}
.icon-heading {
margin: 0;
padding: 0;
text-align: center;
font-size: 20px;
}
.icon-text {
margin: 0;
padding: 0;
text-align: center;
}
.intro-text {
font-size: 1rem;
max-width: 600px;
margin: auto;
padding: 10px;
margin-bottom: 30px;
}
.home-icon:hover {
opacity: 0.7;
background-color: black;
}














<!DOCTYPE html>
<html lang="en-gb">

<head>
    <meta charset="utf-8">
    <title>The Students Guide to Manchester</title>
    <meta name="description" content="By students, for students. Our comprehensive guide is developed to showcase what makes Manchester such a desirable location to study in.">
    <meta keywords="Manchester, students, MMU, guide,">
    <meta name="geo.position" content="53.4692;2.2369">
    <meta name="geo.placename" content="Geoffrey Manton building">

    <meta name="geo.region" content="ISO 3166-2:GB">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <link rel="stylesheet" href="stylesheet.css">
<style>

</style>

</head>
<body>

<p class=skiplinks> <a href="#content">Skip to content</a> <a href="#navigation">Skip to navigation</a> </p>


<a href="#menu" class="menu-link">Menu</a>

        <nav class="menu" id="menu" role="navigation">
            <ul>
                <li><a href="index.html">Home</a></li>
                <li class="has-sub-menu"><a aria-haspopup="true">University</a>
                    <ul class="sub-menu">
                        <li><a href="revision.html">Revision</a></li>
                        
                        <li><a href="social.html">Social</a></li>
                        <li><a href="eqguide.html">The Essentials</a></li>
                        <li><a href="applications.html">Applications</a></li>
                        
                    </ul>
                </li>
                <li><a href="finance.html">Finance</a></li>
                <li class="has-sub-menu"><a href="#" aria-haspopup="true">Living</a>
                    <ul class="sub-menu">
                        <li><a href="hallshouses.html">Halls and Houses</a></li>
                        <li><a href="transport.html">Safety</a></li>
                        <li><a href="social.html">Social</a></li>
                    </ul>
                </li>
                <li class="has-sub-menu"><a aria-haspopup="true">Entertainment</a>
                    <ul class="sub-menu">
                        <li><a href="sports.html" >Sports</a></li>
                        
                        <li><a href="nclubs.html" >Night Clubs</a></li>
                        
   </ul>
                </li>
                <li><a href="health.html" >Health</a></li>
                <li><a href="transport.html" >Transport</a></li>
                <li><a href="food.html" title="">Food</a></li>
                <li><a href="creators.html" title="#">Creators</a></li>

            </ul>
        </nav>
    <script>
    $(document).ready( function(e) {

    var $menu = $('#menu'),
      $menulink = $('.menu-link'),
      $menuTrigger = $('.has-sub-menu > a');

    $menulink.click(function(e) {
        e.preventDefault();
        $menulink.toggleClass('active');
        $menu.toggleClass('active');
    });

    $menuTrigger.click(function(e) {
        e.preventDefault();
        var $this = $(this);
        $this.toggleClass('active').next('ul').toggleClass('active');
    });
    e.preventDefault();

});
    </script>


    <section class="page-content" id="content" role="main">

<div class="home-background">
<h1 class="main-heading">The Students Guide to Manchester</h1>
<h3 class="sub-heading">Getting you through the university experience</h3>
<p class="intro-text">Welcome to our comprehensive guide to the city of Manchester by students for students. This site provides you with a vast and insightful resource designed to help you transition smoothly throughout your university experience.</p>
<div class="thirds">
<div>
<a href="university.php"></a>
<h6 class="icon-heading">University</h6>
<p class="icon-text">First step, get your place!</p>
</div>
<div>
<a href="hallshouses.php"></a>
<h6 class="icon-heading">Living</h6>
<p class="icon-text">Next, find your house!</p>
</div>
<div>
<a href="social.php"></a>
<h6 class="icon-heading">Socializing</h6>
<p class="icon-text">Finally, find some friends!</p>
</div>
</div>
</div>

<p>Here you can find life hacks and the most essential, up-to-date answers to the questions first year students often have. We strive to cover an extensive range of popular topics to help construct a more pleasant experience whilst attending Manchester Metropolitan such as how to live on a budget, which societies exist and how to join one as well as the easiest way to transverse the city amongst many other matters.</p>





    <footer class="page-footer" role="contentinfo">
        <p>&copy; <a href="http://www.mmu.ac.uk/" title="MMU homepage">MMU 2017</a> | THIS IS STUDENT COURSEWORK | TUTOR <a href="mailto:r.eskins@mmu.ac.uk">Richard Eskins</a> | <a href="http://validator.w3.org/check?uri=referer" title="W3C HTML Validation Service">Valid HTML</a> </p>
    </footer>
</section>
</body>
</html>




________________________________

**Pull request merged**
